name: Deploy Azure Function

on:
  push:
    branches:
      - master    # ou 'main' se for o nome do seu branch principal

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x  # ou 6.0.x dependendo do seu projeto

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release --no-restore

      - name: Publish
        run: dotnet publish ./GcKakaoWebGuideAPI/GcKakaoWebGuideAPI.csproj --configuration Release --output ./publish


      - name: Deploy to Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: GcKakaoWebGuideAPI20250725020510
          package: ./publish
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
