name: Deploy Azure Function (.NET)

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instala o .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Restaura dependências
        run: dotnet restore

      - name: Build do projeto
        run: dotnet build --configuration Release --no-restore

      - name: Publica o projeto
        run: dotnet publish ./GcKakaoWebGuideAPI/GcKakaoWebGuideAPI.csproj --configuration Release --output ./publish

      - name: Faz deploy na Azure Function App
        uses: Azure/functions-action@v1
        with:
          app-name: gckakaowebguideapi20250725020510
          package: ./publish
          publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}
